development:
  clients:
    default:
      database: mongo
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: treestats-test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
