name: "deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "Starting deploy..."
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to production
        id: push
        uses: dokku/github-action@master
        with:
          git_remote_url: "dokku@treestats.net:22:treestats-production"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          continue_on_failure: true
      - name: Notify Discord
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "Outcome of deploy: ${{ steps.push.outcome}}"
